description = "The Rails Cloud Native Buildpacks builder is optimized for Ruby On Rails applications."

[[buildpacks]]
id      = "io.avarteqgmbh.buildpacks.git-ssh"
uri     = "../git-ssh-buildpack"

[[buildpacks]]
id      = "com.anynines.buildpacks.rvm"
uri     = "../rvm-bash-cnb"

[[buildpacks]]
id      = "paketo-buildpacks/procfile"
uri     = "../procfile"

[[buildpacks]]
id      = "paketo-buildpacks/node-engine"
uri     = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.199/node-engine-v0.0.199.tgz"

[[buildpacks]]
id      = "paketo-buildpacks/npm"
uri     = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.25/npm-v0.1.25.tgz"

[[buildpacks]]
id      = "paketo-buildpacks/yarn-install"
uri     = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.34/yarn-install-v0.1.34.tgz"

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/npm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/yarn-install"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cloudfoundry/build:full-cnb"
run-image = "cloudfoundry/run:full-cnb"
