description = "The Rails Cloud Native Buildpacks builder is optimized for Ruby On Rails applications."

[[buildpacks]]
id      = "io.avarteqgmbh.buildpacks.git-ssh"
version = "0.5.1"
uri     = "../git-ssh-buildpack"

[[buildpacks]]
id      = "com.anynines.buildpacks.rvm"
version = "0.0.5"
uri     = "../rvm-bash-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.procfile"
version = "v1.1.12"
uri     = "../procfile-cnb"

[[buildpacks]]
id      = "paketo-buildpacks/node-engine"
version = "v0.0.192"
uri     = "../node-engine-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.npm"
version = "v0.1.21"
uri     = "../npm-cnb"

[[buildpacks]]
id      = "paketo-buildpacks/yarn-install"
version = "v0.1.32"
uri     = "../yarn-cnb"

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "org.cloudfoundry.npm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/yarn-install"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cloudfoundry/build:full-cnb"
run-image = "cloudfoundry/run:full-cnb"
