description = "The Rails Cloud Native Buildpacks builder is optimized for Ruby On Rails applications."

[[buildpacks]]
id      = "com.anynines.buildpacks.gitcredentials"
uri     = "/Users/khaledblah/go/src/github.com/avarteqgmbh/gitcredentials"

[[buildpacks]]
id      = "com.anynines.buildpacks.rvm"
uri     = "/Users/khaledblah/go/src/github.com/avarteqgmbh/rvm-cnb"

[[buildpacks]]
id      = "com.anynines.buildpacks.rvm-bundler"
uri     = "/Users/khaledblah/go/src/github.com/avarteqgmbh/rvm-bundler-cnb"

[[buildpacks]]
id      = "paketo-buildpacks/procfile"
uri     = "/Users/khaledblah/go/src/github.com/paketo-buildpacks/procfile"

[[buildpacks]]
id      = "paketo-buildpacks/node-engine"
uri     = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.210/node-engine-0.0.210.tgz"

[[buildpacks]]
id      = "paketo-buildpacks/npm"
uri     = "https://github.com/paketo-buildpacks/npm/releases/download/v0.1.38/npm-0.1.38.tgz"

[[buildpacks]]
id      = "paketo-buildpacks/yarn-install"
uri     = "https://github.com/paketo-buildpacks/yarn-install/releases/download/v0.1.48/yarn-install-0.1.48.tgz"

[[order]]
    [[order.group]]
    id = "com.anynines.buildpacks.gitcredentials"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/npm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm-bundler"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "com.anynines.buildpacks.gitcredentials"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/yarn-install"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm-bundler"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "com.anynines.buildpacks.gitcredentials"
    optional = true

    [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm-bundler"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "com.anynines.buildpacks.gitcredentials"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm-bundler"

    [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cloudfoundry/build:full-cnb"
run-image = "cloudfoundry/run:full-cnb"

# build-image = "paketobuildpacks/build:full-cnb-cf"
# run-image = "paketobuildpacks/run:full-cnb-cf"
