description = "The Rails Cloud Native Buildpacks builder is optimized for Ruby On Rails applications."

[[buildpacks]]
id      = "io.avarteqgmbh.buildpacks.git-ssh"
version = "0.5.1"
uri     = "../git-ssh-buildpack"

[[buildpacks]]
id      = "com.anynines.buildpacks.rvm"
version = "0.0.5"
uri     = "../rvm-bash-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.procfile"
version = "v1.1.11"
uri     = "../procfile-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.nodejs"
version = "v2.0.4"
uri     = "../nodejs-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.node-engine"
version = "0.0.160"
uri     = "../node-engine-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.npm"
version = "0.1.3"
uri     = "../npm-cnb"

[[buildpacks]]
id      = "org.cloudfoundry.yarn"
version = "0.1.4"
uri     = "../yarn-cnb"

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "org.cloudfoundry.npm"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "org.cloudfoundry.yarn"

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "org.cloudfoundry.node-engine"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[[order]]
    [[order.group]]
    id = "io.avarteqgmbh.buildpacks.git-ssh"
    optional = true

    [[order.group]]
    id = "com.anynines.buildpacks.rvm"

    [[order.group]]
    id = "org.cloudfoundry.procfile"
    optional = true

[stack]
id = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cloudfoundry/build:full-cnb"
run-image = "cloudfoundry/run:full-cnb"
